# Generated by Django 5.1 on 2024-09-16 22:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, choices=[('Kurucu', 'Kurucu'), ('Yönetici', 'Yönetici'), ('Yetkili', 'Yetkili'), ('Destek', 'Destek'), ('Kullanıcı', 'Kullanıcı')], default='Kullanıcı', max_length=15, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('support_given', models.PositiveIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Bu kullanıcının ait olduğu gruplar. Bir kullanıcı, ait olduğu her grubun tüm izinlerini alacaktır.', related_name='custom_user_groups', to='auth.group', verbose_name='Gruplar')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Bu kullanıcı için belirli izinler.', related_name='custom_user_permissions', to='auth.permission', verbose_name='Kullanıcı izinleri')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supportive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_team_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChatRoom',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('other_info', models.TextField()),
                ('contract_start_date', models.DateTimeField(auto_now_add=True)),
                ('contract_end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=255, null=True)),
                ('expiry_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.company'),
        ),
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_title', models.CharField(max_length=200)),
                ('error_description', models.TextField()),
                ('error_screenshot', models.ImageField(blank=True, null=True, upload_to='error_screenshots/')),
                ('error_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.company')),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_1', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_2', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_3', models.CharField(blank=True, max_length=255, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='OutgoingReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OutgoingReasons',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_calculation', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('average_cost', 'Ortalama Maliyet'), ('specific_identification', 'Belirli Tanımlama'), ('standard_costing', 'Standart Maliyetleme'), ('moving_average', 'Hareketli Ortalama'), ('weighted_average', 'Ağırlıklı Ortalama'), ('replacement_cost', 'Yenileme Maliyeti')], default='fifo', max_length=50)),
                ('is_inventory', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
            options={
                'db_table': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_company', models.BooleanField(default=False)),
                ('list_company', models.BooleanField(default=False)),
                ('set_agreement_date', models.BooleanField(default=False)),
                ('set_company_status', models.BooleanField(default=False)),
                ('access_to_bugs', models.BooleanField(default=False)),
                ('add_bill', models.BooleanField(default=False)),
                ('add_inventory', models.BooleanField(default=False)),
                ('add_parameter', models.BooleanField(default=False)),
                ('add_product', models.BooleanField(default=False)),
                ('add_category', models.BooleanField(default=False)),
                ('add_seller', models.BooleanField(default=False)),
                ('add_outgoing', models.BooleanField(default=False)),
                ('add_unit', models.BooleanField(default=False)),
                ('add_user', models.BooleanField(default=False)),
                ('update_user', models.BooleanField(default=False)),
                ('update_category', models.BooleanField(default=False)),
                ('delete_unit', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('delete_outgoing_reason', models.BooleanField(default=False)),
                ('access_to_reports', models.BooleanField(default=False)),
                ('paid_unpaid_bill', models.BooleanField(default=False)),
                ('payment_seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('average_cost', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_critical', models.BooleanField(default=False)),
                ('prevent_stock_negative', models.BooleanField(default=False)),
                ('critical_stock_level', models.IntegerField(default=0)),
                ('is_inventory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OutgoingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('processing_time', models.DateTimeField(auto_now_add=True)),
                ('outgoing_total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('is_inventory', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_bills', to='stock.inventory')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outgoing_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product')),
            ],
            options={
                'db_table': 'OutgoingBill',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('discount_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('discount_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_inventory', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_1', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_2', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_3', models.CharField(blank=True, max_length=255, null=True)),
                ('row_total', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=255, null=True)),
                ('processing_time', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.bill')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'BillItem',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('receivable', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True)),
                ('debt', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.seller'),
        ),
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Çıkan Miktar')),
                ('incoming_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Giren Miktar')),
                ('processing_time', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('current_stock', models.IntegerField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Toplam Tutar')),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('incoming_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.bill', verbose_name='Giriş Faturası')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outgoing_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingbill', verbose_name='Çıkış Faturası')),
                ('outgoing_reasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product', verbose_name='Ürün')),
            ],
            options={
                'db_table': 'StockTransactions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('is_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Unit',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.unit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.unit'),
        ),
    ]
