# Generated by Django 5.0.6 on 2024-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_seller_bill_created_date_bill_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
