# Generated by Django 5.0.6 on 2024-06-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_seller_debt_alter_seller_receivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
