# Generated by Django 5.0.6 on 2024-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
