# Generated by Django 5.0.6 on 2024-06-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_billitem_price_alter_billitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='incoming_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='outgoing_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
