# Generated by Django 5.0.6 on 2024-06-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stock_bill_alter_stock_incoming_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.bill')),
                ('outgoing_reasons', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
