# Generated by Django 5.0.6 on 2024-06-24 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_outgoingreasons_incomingstock_outgoingstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='outgoing_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
