# Generated by Django 5.0.6 on 2024-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_outgoingstock_bill_outgoingstock_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
