# Generated by Django 5.0.6 on 2024-06-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_currentstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingstock',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='incomingstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outgoingstock',
            name='outgoing_reasons',
        ),
        migrations.RemoveField(
            model_name='outgoingstock',
            name='product',
        ),
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('outgoing_quantity', models.IntegerField()),
                ('incoming_quantity', models.IntegerField()),
                ('processing_time', models.DateTimeField()),
                ('outgoing_bill', models.CharField(max_length=255)),
                ('incoming_bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.bill')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentStock',
        ),
        migrations.DeleteModel(
            name='IncomingStock',
        ),
        migrations.DeleteModel(
            name='OutgoingStock',
        ),
    ]
