# Generated by Django 5.0.6 on 2024-06-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_stocktransactions_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='incoming_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='outgoing_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
