# Generated by Django 5.0.6 on 2024-06-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_stocktransactions_incoming_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactions',
            name='outgoing_reasons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons'),
            preserve_default=False,
        ),
    ]
