# Generated by Django 5.0.6 on 2024-06-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stocktransactions_outgoing_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='incoming_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.bill'),
        ),
    ]
