# Generated by Django 5.0.6 on 2024-06-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_alter_stocktransactions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='outgoing_reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons'),
        ),
    ]
