# Generated by Django 5.0.6 on 2024-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_stocktransactions_outgoing_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
