# Generated by Django 5.0.6 on 2024-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_product_allow_negative_stock_product_is_critical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='allow_negative_stock',
            new_name='prevent_stock_negative',
        ),
        migrations.AddField(
            model_name='product',
            name='critical_stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
