# Generated by Django 5.0.6 on 2024-06-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_rename_allow_negative_stock_product_prevent_stock_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingreasons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
