# Generated by Django 5.0.6 on 2024-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_outgoingreasons_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactions',
            name='current_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
