# Generated by Django 5.0.6 on 2024-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stocktransactions_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
