# Generated by Django 5.0.6 on 2024-07-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('processing_time', models.DateTimeField(auto_now_add=True)),
                ('outgoing_reasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingreasons')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product')),
            ],
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='outgoing_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingbill'),
        ),
    ]
