# Generated by Django 5.0.6 on 2024-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_outgoingbill_alter_stocktransactions_outgoing_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingbill',
            old_name='outgoing_reasons',
            new_name='outgoing_reason',
        ),
        migrations.AlterField(
            model_name='outgoingbill',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
