# Generated by Django 5.0.6 on 2024-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_rename_outgoing_reasons_outgoingbill_outgoing_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingbill',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
