# Generated by Django 5.0.6 on 2024-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_parameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
