# Generated by Django 5.0.6 on 2024-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_seller_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
