# Generated by Django 5.0.6 on 2024-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock', '0044_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Bu kullanıcının ait olduğu gruplar. Bir kullanıcı, ait olduğu her grubun tüm izinlerini alacaktır.', related_name='custom_user_groups', to='auth.group', verbose_name='Gruplar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Bu kullanıcı için belirli izinler.', related_name='custom_user_permissions', to='auth.permission', verbose_name='Kullanıcı izinleri'),
        ),
    ]
