# Generated by Django 5.0.6 on 2024-07-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
