# Generated by Django 5.0.6 on 2024-07-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
