# Generated by Django 5.0.6 on 2024-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
