# Generated by Django 5.0.6 on 2024-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0050_company_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='stock_issues',
        ),
        migrations.AddField(
            model_name='parameter',
            name='average_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='fifo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='lifo',
            field=models.BooleanField(default=False),
        ),
    ]
