# Generated by Django 5.0.6 on 2024-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_remove_parameter_stock_issues_parameter_average_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='fifo',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='lifo',
        ),
        migrations.AddField(
            model_name='parameter',
            name='cost_calculation',
            field=models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('average_cost', 'Ortalama Maliyet')], default='fifo', max_length=20),
        ),
    ]
