# Generated by Django 5.0.6 on 2024-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0052_remove_parameter_average_cost_remove_parameter_fifo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='cost_calculation',
            field=models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('average_cost', 'Srtalama Maliyet')], default='fifo', max_length=20),
        ),
    ]
