# Generated by Django 5.0.6 on 2024-07-27 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0056_remove_user_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.IntegerField(),
        ),
    ]
