# Generated by Django 5.0.6 on 2024-07-28 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_bill_is_create_billitem_is_create_category_is_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to='stock.user'),
        ),
        migrations.AlterField(
            model_name='outgoingbill',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='outgoingreasons',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.user'),
        ),
    ]
