# Generated by Django 5.0.6 on 2024-07-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_alter_bill_is_create_alter_billitem_is_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='row_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
