# Generated by Django 5.0.6 on 2024-07-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_billitem_row_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingbill',
            name='outgoing_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
