# Generated by Django 5.0.6 on 2024-07-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0063_stocktransactions_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='incoming_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.bill', verbose_name='Giriş Faturası'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='incoming_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Giren Miktar'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='outgoing_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.outgoingbill', verbose_name='Çıkış Faturası'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='outgoing_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Çıkan Miktar'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='processing_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Toplam Tutar'),
        ),
    ]
