# Generated by Django 5.0.6 on 2024-07-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0066_product_is_inventory_recipe_recipeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_1', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_2', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode_3', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.unit')),
            ],
        ),
    ]
