# Generated by Django 5.0.6 on 2024-07-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0067_remove_product_serial_number_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode_3',
        ),
        migrations.AddField(
            model_name='billitem',
            name='barcode_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='barcode_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='barcode_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
