# Generated by Django 5.0.6 on 2024-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0069_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='row_total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=255, null=True),
        ),
    ]
