# Generated by Django 5.0.6 on 2024-07-31 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0070_alter_billitem_row_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.company'),
            preserve_default=False,
        ),
    ]
