# Generated by Django 5.0.6 on 2024-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0071_inventory_bill_inventory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingbill',
            name='is_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
