# Generated by Django 5.0.6 on 2024-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_outgoingbill_is_inventory_outgoingbill_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
