# Generated by Django 5.0.6 on 2024-08-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0073_inventory_is_released'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'company')},
        ),
    ]
