# Generated by Django 5.0.6 on 2024-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0075_remove_user_company_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
