# Generated by Django 5.0.6 on 2024-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0080_permission_add_bill_permission_add_definitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='add_parameter',
            field=models.BooleanField(default=False),
        ),
    ]
