# Generated by Django 5.0.6 on 2024-08-12 09:05

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0082_user_tag_alter_permission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stock.models.get_upload_to),
        ),
    ]
