# Generated by Django 5.0.6 on 2024-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0083_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='add_definitions',
            new_name='add_category',
        ),
        migrations.AddField(
            model_name='permission',
            name='add_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='add_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='add_unit',
            field=models.BooleanField(default=False),
        ),
    ]
