# Generated by Django 5.0.6 on 2024-08-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0087_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
