# Generated by Django 5.1 on 2024-08-14 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0096_chatroom_status_chatroom_supportive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='supportive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_team_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
