# Generated by Django 5.1 on 2024-08-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0097_alter_chatroom_supportive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='support_given',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
