# Generated by Django 5.1 on 2024-08-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0099_chatroom_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
