# Generated by Django 5.1 on 2024-08-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0101_chatroom_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatroom',
            table='ChatRoom',
        ),
    ]
