# Generated by Django 5.1 on 2024-08-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0102_alter_chatroom_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
