# Generated by Django 5.1 on 2024-08-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0103_alter_message_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='bill',
            table='Bill',
        ),
        migrations.AlterModelTable(
            name='billitem',
            table='BillItem',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AlterModelTable(
            name='outgoingbill',
            table='OutgoingBill',
        ),
        migrations.AlterModelTable(
            name='outgoingreasons',
            table='OutgoingReasons',
        ),
        migrations.AlterModelTable(
            name='parameter',
            table='Parameter',
        ),
        migrations.AlterModelTable(
            name='permission',
            table='Permission',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='Recipe',
        ),
        migrations.AlterModelTable(
            name='recipeproduct',
            table='RecipeProduct',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='Seller',
        ),
        migrations.AlterModelTable(
            name='stocktransactions',
            table='StockTransactions',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='Unit',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
