# Generated by Django 5.1 on 2024-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0104_alter_user_unique_together_alter_bill_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='list_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='set_agreement_date',
            field=models.BooleanField(default=False),
        ),
    ]
