# Generated by Django 5.1 on 2024-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0105_permission_list_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.CharField(blank=True, choices=[('Kurucu', 'Kurucu'), ('Yönetici', 'Yönetici'), ('Yetkili', 'Yetkili'), ('Destek', 'Destek'), ('User', 'User')], max_length=15, null=True),
        ),
    ]
