# Generated by Django 5.1 on 2024-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0108_alter_user_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='update_unit',
            field=models.BooleanField(default=False),
        ),
    ]
