# Generated by Django 5.1 on 2024-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0110_permission_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='access_to_reports',
            field=models.BooleanField(default=False),
        ),
    ]
