# Generated by Django 5.1 on 2024-08-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0111_permission_access_to_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='update_unit',
        ),
    ]
