# Generated by Django 5.1 on 2024-08-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0112_remove_permission_update_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
