# Generated by Django 5.1 on 2024-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0113_alter_seller_debt_alter_seller_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='update_user',
            field=models.BooleanField(default=False),
        ),
    ]
