# Generated by Django 5.1 on 2024-08-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0114_permission_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
