# Generated by Django 5.1 on 2024-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0115_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='delete_product',
            field=models.BooleanField(default=False),
        ),
    ]
